### ISSUE TITLE
missing field `type` for key `network`

### ISSUE THREAD

**Issue by vmodha** [holochain/holochain-basic-chat#66]
I'm attempting to install the chat on my local machine, so far everything been going well, I'm currently at the step where I've just updated 'my-conductor-config.toml' with the results of 'hc keygen'.

Now when attempting the next step 'holochain -c ./my-conductor-config.toml' I'm getting the following error.

```
holochain -c ./my-conductor-config.toml
Using config path: ./my-conductor-config.toml
Error while trying to boot from config: IoError("Error loading configuration: missing field `type` for key `network`")
```

Any help would be appreciated, I can add the field 'type' into network, I just dont know what to populate it with.

**Comment by elegant651** [comment]
In my case, it was resolved after reinstalling holochain environment refer to the manual : https://developer.holochain.org/start.html
hc 0.0.28-alpha1, holochain 0.0.28-alpha1

**Comment by vmodha** [comment]
Thank you, which version of Nix-Shell are you using? Did you follow thier instructions with "  nix-shell https://github.com/holochain/holochain-rust/archive/3b42375dc31442b62855cff8c339a6422c447176.tar.gz"

I ask because after updating to holochain 0.0.28... I'm still getting the same 'missing field [type]' error.

**Comment by vmodha** [comment]
> In my case, it was resolved after reinstalling holochain environment refer to the manual : https://developer.holochain.org/start.html
> hc 0.0.28-alpha1, holochain 0.0.28-alpha1

Thank you, which version of Nix-Shell are you using? Did you follow thier instructions with " nix-shell https://github.com/holochain/holochain-rust/archive/3b42375dc31442b62855cff8c339a6422c447176.tar.gz"

I ask because after updating to holochain 0.0.28... I'm still getting the same 'missing field [type]' error.

**Comment by elegant651** [comment]
nix-env (Nix) 2.2.2, I use. 
Yes, I followed that link to install, but should have update upper version. And, I got the 'missing field' error as well. so, just paste it from other agent config file like this.

[network]
type = "n3h"
n3h_mode = "REAL"
n3h_path = ""
n3h_persistence_path = "/tmp"
bootstrap_nodes = []
n3h_log_level = "t"

It seems work, but now should find out how to connect between ui and conductor. 
poor documentation

**Comment by vmodha** [comment]
> nix-env (Nix) 2.2.2, I use.
> Yes, I followed that link to install, but should have update upper version. And, I got the 'missing field' error as well. so, just paste it from other agent config file like this.
> 
> [network]
> type = "n3h"
> n3h_mode = "REAL"
> n3h_path = ""
> n3h_persistence_path = "/tmp"
> bootstrap_nodes = []
> n3h_log_level = "t"
> 
> It seems work, but now should find out how to connect between ui and conductor.
> poor documentation

Thanks, yes I had originally made it this far too, I'll be excited to get this working as well. I've emailed you to see if you'd like to play on this together.
